const app = document.getElementById("app");

const model = {
  app: {
    page: "main", //'logIn', 'profile', 'profileShuffle', 'DM', 'createProfile',
    loggedInUserId: null,
    isLoggedIn: false,
  },
  input: {
    logIn: {
      username: "",
      pwd: "",
    },
    profiles: {
      id: null,
      username: "",
      pwd: "",
      repeatPwd: "",
      name: "",
      age: "",
      city: "",
      interests: "",
      bio: "",
      img: "",
    },
    DM: {
      id: null,
      userMessage: "",
      recivedMessage: "",
    },
  },
  profiles: [
    {
      id: 0,
      isLoggedIn: false,
      username: "odda64",
      pwd: "1234",
      name: "Odd Anton",
      age: 60,
      location: "Stathelle",
      interests: ["Båt", "Whiskey"],
      bio: "På utkikk etter ei ung snelle som vil dele et glass whiskey på båten min. Kan ta deg med hvor som helst.",
      albumImg: [
        "sources/images/datingapp-bilder/odd-anton-profile.jpg",
        "sources/images/datingapp-bilder/odd-anton.jpg",
        "sources/images/datingapp-bilder/odd-anton1.jpg",
        "sources/images/datingapp-bilder/susanne2.jpg",
        "sources/images/datingapp-bilder/odd-anton3.jpg",
      ],
    },
    {
      id: 1,
      isLoggedIn: false,
      username: "leoi",
      pwd: "K8z7D424",
      name: "Gunn",
      age: 37,
      location: "Fredrikstad",
      interests: ["charterturer", "chiahuahua"],
      bio: "Elsker billige charterturer med hundene mine Elise & Iver. På tur pleier vi å drikke vin, spise god mat å gå lange romantiske turer på stranden, både med og uten solnedgang. Hadde det vert hyggelig å dele dette med Elise og meg så ta kontakt!",
      albumImg: [
        "sources/images/datingapp-bilder/gunn-profile.jpg",
        "sources/images/datingapp-bilder/gunn.jpg",
        "sources/images/datingapp-bilder/gunn1.jpg",
        "sources/images/datingapp-bilder/gunn2.jpg",
        "sources/images/datingapp-bilder/gunn3.jpg",
      ],
    },
    {
      id: 2,
      isLoggedIn: false,
      username: "violin",
      pwd: "8YDtBpwz",
      name: "Giselle",
      age: 49,
      location: "Bergen",
      interests: ["politikk", "håndarbeid"],
      bio: "Bestemor til 4 skjønne barn. Politisk aktiv så ikke så mye hjemme, ser etter noen som vil holde meg med selvskap de få gangene jeg har mulighet til å sitte hjemme å drive med håndarbeid. Vil beskrive med selv som en meget alturistisk person.",
      albumImg: [
        "sources/images/datingapp-bilder/giselle-profile.jpg",
        "sources/images/datingapp-bilder/giselle.jpg",
        "sources/images/datingapp-bilder/giselle1.jpg",
        "sources/images/datingapp-bilder/giselle2.jpg",
        "sources/images/datingapp-bilder/giselle3.jpg",
      ],
    },
    {
      id: 3,
      isLoggedIn: false,
      username: "nixwind",
      pwd: "jWt5l7Km",
      name: "Isalill",
      age: 28,
      location: "Stavanger",
      interests: ["yoga", "seiling"],
      bio: "Jeg er en avslappet og balansert kvinne som elsker yoga og alt som har med sjøen å gjøre. Yoga gir meg ro og styrke, og jeg liker å starte dagen med en god økt. Når jeg ikke er på teppet, finner du meg ofte ute i seilbåten, hvor jeg nyter friheten og den friske sjøluften. Jeg setter pris på gode samtaler, god mat og tid til å slappe av med venner. Jeg ser etter en eventyrlysten sjel med sans for ro og naturopplevelser.",
      albumImg: [
        "sources/images/datingapp-bilder/isalill-profile.jpg",
        "sources/images/datingapp-bilder/isalill.jpg",
        "sources/images/datingapp-bilder/isalill1.jpg",
        "sources/images/datingapp-bilder/isalill2.jpg",
        "sources/images/datingapp-bilder/isalill3.jpg",
      ],
    },
    {
      id: 4,
      isLoggedIn: false,
      username: "batmanbegins",
      pwd: "jhoHlrzY",
      name: "Monica",
      age: 25,
      location: "Oslo",
      interests: ["poker", "dyre klokker"],
      bio: "Jeg er en profesjonell pokerspiller som er veldig ambisiøs. Jeg elsker spenningen som følger med hvert spill. Utenom poker har jeg utviklet en stor kjærlighet for dyre klokker, og jeg elsker å samle på unike stilige modeller. Jeg setter pris på kvalitet og godt håndverk. Hvis det høres interessant ut, vil jeg gjerne høre fra deg!",
      albumImg: [
        "sources/images/datingapp-bilder/monica-profile.jpg",
        "sources/images/datingapp-bilder/monica.jpg",
        "sources/images/datingapp-bilder/monica1.jpg",
        "sources/images/datingapp-bilder/monica2.jpg",
        "sources/images/datingapp-bilder/monica3.jpg",
      ],
    },
    {
      id: 5,
      isLoggedIn: false,
      username: "fargo",
      pwd: "hqSvRAcR",
      name: "Astrid",
      age: 48,
      location: "Hamar",
      interests: ["barnebarn", "reise"],
      bio: "Livsglad moden kvinne som liker å reise og oppleve nye kulturer. Setter alltid pris på et glass vin og en vakker solnedgang på en strand. Jeg er alltid på jakt etter nye eventyr og gode samtale.Hvis du er klar til å utforske verden sammen med meg så send en melding da vel",
      albumImg: [
        "sources/images/datingapp-bilder/astrid-profile.jpg",
        "sources/images/datingapp-bilder/astrid.jpg",
        "sources/images/datingapp-bilder/astrid1.jpg",
        "sources/images/datingapp-bilder/astrid2.jpg",
        "sources/images/datingapp-bilder/astrid3.jpg",
      ],
    },
    {
      id: 6,
      isLoggedIn: false,
      username: "doggrape",
      pwd: "IJAe0HuA",
      name: "Liv",
      age: 39,
      location: "Hadeland",
      interests: ["vin", "toppturer"],
      bio: "Elsker å tilbringe tid i naturen. Toppturer gir meg den perfekte kombo av trening og naturopplevelser, og jeg nyter å nye høyder. Når jeg ikke er på fjellet er jeg å finne med et glass rødt i hånden, enten hjemme eller med gode venner eller på en koselig restaurant. Hvis du er en eventyrer med sans for gode smaker, håper jeg å høre fra deg!",
      albumImg: [
        "sources/images/datingapp-bilder/liv-profile.jpg",
        "sources/images/datingapp-bilder/liv.jpg",
        "sources/images/datingapp-bilder/liv1.jpg",
        "sources/images/datingapp-bilder/liv2.jpg",
        "sources/images/datingapp-bilder/liv3.jpg",
      ],
    },
    {
      id: 7,
      isLoggedIn: false,
      username: "fitnesssun",
      pwd: "zGrpnT1o",
      name: "Isabelle",
      age: 35,
      location: "Bergen",
      interests: ["svømming", "kaffe"],
      bio: "En ekte livsnyter som elsker å utforske nye restauranter og smake på spennende retter. God mat og godt selvskap er en vinner kombinasjon for meg. Ser etter noen som deler min entusiasme for god mat, vin og mote.",
      albumImg: [
        "sources/images/datingapp-bilder/isabelle-profile.jpg",
        "sources/images/datingapp-bilder/isabelle.jpg",
        "sources/images/datingapp-bilder/isabelle1.jpg",
        "sources/images/datingapp-bilder/isabelle2.jpg",
        "sources/images/datingapp-bilder/isabelle3.jpg",
      ],
    },
    {
      id: 8,
      isLoggedIn: false,
      username: "psycho",
      pwd: "1LgVbqgA",
      name: "Erika",
      age: 35,
      location: "Oslo",
      interests: ["dans", "kattene mine"],
      bio: "Elsker kattene min over alt på jord! Trenger noen som kan holde oss med selvskap. Min andre store lidenskap er dans",
      albumImg: [
        "sources/images/datingapp-bilder/erika-profile.jpg",
        "sources/images/datingapp-bilder/erika.jpg",
        "sources/images/datingapp-bilder/erika1.jpg",
        "sources/images/datingapp-bilder/erika2.jpg",
        "sources/images/datingapp-bilder/erika3.jpg",
      ],
    },
    {
      id: 9,
      isLoggedIn: false,
      username: "owlswan",
      pwd: "HrYQa6gL",
      name: "Susanne",
      age: 25,
      location: "Drammen",
      interests: ["yoga", "trening"],
      bio: "Energisk og kreativ person som elsker å tilbringe tid med venner og utforske nye steder. Jeg ser etter noen som elsker å dele gode stunder sammen. Hvis du er klar for å bli kjent så slide in to my DM",
      albumImg: [
        "sources/images/datingapp-bilder/susanne-profile.jpg",
        "sources/images/datingapp-bilder/susanne.jpg",
        "sources/images/datingapp-bilder/susanne1.jpg",
        "sources/images/datingapp-bilder/susanne2.jpg",
        "sources/images/datingapp-bilder/susanne3.jpg",
      ],
    },
    {
      id: 10,
      isLoggedIn: false,
      username: "steelfox",
      pwd: "qAOhztwN",
      name: "Ingrid",
      age: 30,
      location: "Kløfta",
      interests: ["ridning", "venner"],
      bio: "Livsglad jente som elsker hester. Setter stor pris på gode samtaler, latter og spontane eventyr.",
      albumImg: [
        "sources/images/datingapp-bilder/ingrid-profile.jpg",
        "sources/images/datingapp-bilder/ingrid.jpg",
        "sources/images/datingapp-bilder/ingrid1.jpg",
        "sources/images/datingapp-bilder/ingrid2.jpg",
        "sources/images/datingapp-bilder/ingrid3.jpg",
      ],
    },
  ],
};
